### ISSUE TITLE
WSI Registration not working on MRXS files (due to alpha channel issues)

### ISSUE THREAD

**Issue by maubreville** [ChristianMarzahl/WsiRegistration#4]
MRXS scans are black in areas that have not been scanned, which is compensated by also having an alpha value of zero, however, for the registration this leads to huge problems:

![image](https://user-images.githubusercontent.com/10051592/149473709-ba62d989-54f8-449b-8c24-945bcc1ece25.png)

![image](https://user-images.githubusercontent.com/10051592/149473909-23048ebb-f25b-4660-82fc-8bbe455991a0.png)

**Comment by ChristianMarzahl** [comment]
Dear @maubreville,

thanks for opening the issue. 

Unfortunately, I could not see what kind of issue it is or how it manifests itself from your ticket. I would therefore ask you to describe the ticket in a more reproducible way and provide example slides. 

Furthermore, the MRXS scanner was not part of the publication on which this code is based, so we cannot comment on the quality of the results. 

With kind regards,
Christian

**Comment by maubreville** [comment]
Very good point! I just came across the issue and wondered, if there was an easy solution to fix it. In fact, I was already working on one but somehow did not manage to get it working. 

If you want to get the issue fixed, I can provide you with sample files (both around 800MB).

BTW: Here's the trace of the error:

  File "/Users/../opt/miniconda3/lib/python3.8/site-packages/qt_wsi_reg/registration_tree.py", line 200, in __init__
    self.mean_reg_error, self.sigma2, self.q, self.tf_param = self._get_min_reg_error_hom(self.ptsA, self.ptsB)

  File "/Users/../opt/miniconda3/lib/python3.8/site-packages/qt_wsi_reg/registration_tree.py", line 237, in _get_min_reg_error_hom
    temp_tf_param = tf.AffineTransformation(homography[:2, :2], homography[:2, 2:].reshape(-1))

TypeError: 'NoneType' object is not subscriptable

**Comment by ChristianMarzahl** [comment]
Dear @maubreville ,

this error message means that the method "AffineTransformation" was not able to estimate an affine transformation, most likely due to the methods inability to find matching pairs. Is this a restained slide or a consecutive slide?

I will update the error message, to make it easier to estimate the issue in the future. 

With kind regards,
Christian

**Comment by maubreville** [comment]
It's a restained slide. As indicated above: I think the reason is that the registration can't cope with the use of the alpha channel in MRXS files. For the Jiang method, I just replaced all transparent pixels in the image with white pixels (because transparent indicates "not scanned"), and then it worked again.

So it's very sensible that matching points were not found, since likely the edges of the image are a significant percentage of the keypoints.

**Comment by ChristianMarzahl** [comment]
Dear @maubreville,

I check your files, and the issue is that the SIFT algorithm cannot find matching key points on your images. Please stay tuned for an update on our algorithmic approach. 

With kind regards,
Christiana
