### ISSUE TITLE
errors when following demos or examples

### ISSUE THREAD

**Issue by NicolasNerr** [ChristianMarzahl/WsiRegistration#6]
Hi Mr Marzahl,

Thank you for the tool, I am looking forward to see your new work for the ACROBAT challenge 2022.

I have some troubles when applying the quad tree on .tif/.tiff slides. Just following the code structure of the demo IHC-HE, I cannot use the draw_annotation method because of the following error : TypeError: '>' not supported between instances of 'numpy.ndarray' and 'float'
Moreover, when passing slides path to build the RegistrationQuadTree and when I use the draw_feature_points method, for the majority of the slides I get the message : 'too many indices for array: array is 1-dimensional, but 2 were indexed'. 

As I don't do anything special with the slides beforehand (just passing the path to the method actually), I was wondering if you encountered the same issue, or if you have an idea of where it can happen in the code ? 

These issues prevent me from using the complete tool, and to really perform the desired registration. 

Thank you

**Comment by ChristianMarzahl** [comment]
Dear @NicolasNerr,

The errors you encounter most likely mean that the classical method cannot find matching key points. This is a known issue with SIFT or ORB on consecutive slides as described in the publication.   

The method implemented in this repository will therefore fail on the ACROBAT challenge datasets. 

Is the method working on the demo dataset provided in this repository? https://github.com/ChristianMarzahl/WsiRegistration/tree/main/examples/4Scanner


With kind regards,
Christian

**Comment by NicolasNerr** [comment]
Hello @ChristianMarzahl, 

It might indeed be that not enough matching keypoints are found as the method is working on the demo dataset you mentioned !
Does the method include channel deconvolution before extracting keypoints ? Did not see it in the publication but just to make sure, as it might help to find matching descriptors in corresponding pairs HE/IHC.

Best regards, 
Nicolas

**Comment by ChristianMarzahl** [comment]
Dear @NicolasNerr,

The cone did not contain any channel deconvolution besides the option for changing to use a greyscale image.

On a side note, this repository will not get new features in the future and is only to reproduce the results from the publication.  

I can recommend the [VALIS](https://valis.readthedocs.io/en/latest/) repository for image registration.

**Comment by NicolasNerr** [comment]
Dear @ChristianMarzahl, 

Thank you so much for your time and your answers. I will make sure to check the VALIS repository !

This is non related but if you have 2 more minutes to spare, I was wondering if you know when the replay of the MICCAI session on ACROBAT challenge will be available ? or the publications related to the challenge. 
Unfortunately, I missed the session due to jet lag as I live in France.

Again, thank you so much !

**Comment by ChristianMarzahl** [comment]
Dear @NicolasNerr ,

Unfortunately, I don't have any information regarding both of your questions.
